package be.ordina.jworks.rpsls.game;

public enum GameEvent {

    SPECTATOR_JOINED,
    PLAYER_ONE_JOINED,
    PLAYER_TWO_JOINED,
    PLAYER_ONE_ROCK,
    PLAYER_ONE_PAPER,
    PLAYER_ONE_SCISSORS,
    PLAYER_ONE_LIZARD,
    PLAYER_ONE_SPOCK,
    PLAYER_TWO_ROCK,
    PLAYER_TWO_PAPER,
    PLAYER_TWO_SCISSORS,
    PLAYER_TWO_LIZARD,
    PLAYER_TWO_SPOCK,

}
